# Generated by Django 3.0.6 on 2020-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20200606_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerrequest',
            name='inn_company',
            field=models.TextField(),
        ),
    ]
