# Generated by Django 3.0.6 on 2020-06-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20200606_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ya_num',
            field=models.TextField(default='-1'),
        ),
    ]
