# Generated by Django 3.0.5 on 2020-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0024_auto_20200508_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='role',
            field=models.TextField(default='Житель'),
        ),
    ]
