# Generated by Django 3.0.5 on 2020-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0028_comment_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='html_text',
            field=models.TextField(default='text', editable=False),
            preserve_default=False,
        ),
    ]
