# Generated by Django 3.0.5 on 2020-05-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0029_comment_html_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='markdown_text',
        ),
    ]
