# Generated by Django 3.0.3 on 2020-04-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_company_house_manager_tennant'),
        ('common', '0003_delete_feedback'),
    ]

    operations = [
    ]
