# Generated by Django 3.0.3 on 2020-05-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_feedback'),
        ('common', '0004_merge_20200418_1648'),
    ]

    operations = [
    ]
