# Generated by Django 3.0.3 on 2020-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_merge_20200522_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='yourmail',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
