# Generated by Django 3.0.5 on 2020-05-30 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0003_auto_20200604_0128'),
    ]

    operations = [
    ]
